### PR TITLE
Fix KeyError: '_indexOfStartingAt'

### PR DESCRIPTION
**Pull request by mikesol**

### CODE REVIEW

**Comment by thautwarm** [comment]
Sorry, I missed my notifications today. I'll check this tonight.

**Comment by Hong-Xiang** [comment]
Thanks for your PR. It seems that there are two `just` arguments: the argument of  `_indexOfStartingAt` and the first lambda function. Could you please remove one of them?

**Comment by mikesol** [comment]
Done, thanks.

**Comment by Hong-Xiang** [comment]
@mikesol , thanks for your update.

**Pull request merged**
